import { Inter } from "next/font/google";
import "./globals.css";
import clsx from "clsx";
import FireFliesBackground  from "./Components/FireFliesBackground";
import { Sound } from "./Components/Sound";

const inter = Inter({
  subsets: ["latin"],
  variable:"--font-inter",
});

export const metadata = {
  title: "My Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={clsx(inter.variable,"bg-background text-foreground font-inter")}>{children}
      <FireFliesBackground/>
      <Sound/>
      <div id="my-modal"/>
      </body>
    </html>
  );
}
